// Generated by scripts/service-sync.mjs from the server's OpenAPI document. Do not edit.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_artifacts"];
        put?: never;
        post: operations["create_artifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backfills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_backfill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backfills/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_backfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backfills/{id}/prefilter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prefilter_backfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["failed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["work"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_events"];
        put?: never;
        post: operations["emit_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_flows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_flow"];
        put?: never;
        post?: never;
        delete: operations["delete_flow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_backfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/backfills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_backfills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pause_flow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resume_flow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_run_for_flow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_schedules"];
        put?: never;
        post: operations["create_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{id}/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["upcoming_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/acquire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acquire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_rules"];
        put?: never;
        post: operations["create_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_rule"];
        put?: never;
        post?: never;
        delete: operations["delete_rule"];
        options?: never;
        head?: never;
        patch: operations["patch_rule"];
        trace?: never;
    };
    "/api/rules/{id}/expectations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rule_expectations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{id}/firings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rule_firings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_runs"];
        put?: never;
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete: operations["delete_run"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run_input"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resume_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transition_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_schedule"];
        options?: never;
        head?: never;
        patch: operations["patch_schedule"];
        trace?: never;
    };
    "/api/schedules/{sid}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pause_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{sid}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resume_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["server_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_settings"];
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_task_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_task_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-runs/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task_run_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task_run_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_variables"];
        put?: never;
        post: operations["create_variable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_variable"];
        put?: never;
        post?: never;
        delete: operations["delete_variable"];
        options?: never;
        head?: never;
        patch: operations["patch_variable"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcquireRequest: {
            resources: Record<string, never>;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            wait_ms?: number;
        };
        AfterSpec: {
            /** @description The first upstream (kept for 1.0 payloads and the run details link). */
            flow: string;
            /** @description Every upstream; empty for rows written before fan-in existed. */
            flows?: string[];
            /** @description Parameter that identifies a batch: the downstream runs once per value. */
            key?: string | null;
            parameters?: Record<string, never>;
        };
        ArtifactBody: {
            data: Record<string, never>;
            key?: string | null;
            kind: string;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            task_run_id?: number | null;
        };
        /** @description One artifact in the cross-run listing, with its run's identity. */
        ArtifactListItem: components["schemas"]["ArtifactRow"] & {
            flow_name: string;
            project: string;
            run_name: string;
        };
        /** @description A stored artifact attached to a run and optionally a task run. */
        ArtifactRow: {
            created_at: components["schemas"]["i64"];
            data: Record<string, never>;
            external_id: components["schemas"]["Id"];
            /** Format: int64 */
            id: number;
            key?: string | null;
            /** @description `markdown`, `table`, `progress`, `link`, or `image`. */
            kind: string;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            task_run_id?: number | null;
            updated_at: components["schemas"]["i64"];
        };
        ArtifactsPage: {
            items: components["schemas"]["ArtifactListItem"][];
            /** Format: int64 */
            next_cursor?: number | null;
        };
        Backfill: {
            cancelled: boolean;
            /** Format: int64 */
            concurrency: number;
            created_at: components["schemas"]["i64"];
            end_value: string;
            external_id: components["schemas"]["Id"];
            extra_parameters?: Record<string, never>;
            /** Format: int64 */
            flow_id: number;
            /** Format: int64 */
            id: number;
            /** Format: double */
            interval_secs: number;
            parameter: string;
            start_value: string;
            /** Format: int64 */
            total: number;
        };
        BackfillBody: {
            /** Format: int64 */
            concurrency?: number | null;
            end: string;
            extra_parameters?: Record<string, never>;
            /** @description Seconds, or a shorthand like `1d`, `12h`, `30m`. Default one day. */
            interval?: unknown;
            parameter: string;
            reverse?: boolean;
            start: string;
        };
        BackfillStatus: components["schemas"]["Backfill"] & {
            counts: {
                [key: string]: number;
            };
            tag: string;
        };
        /** @enum {string} */
        CatchupPolicy: "skip" | "latest" | "all";
        Counts: {
            /**
             * Format: int64
             * @description Number of non-terminal runs held in memory.
             */
            active: number;
            /** @description Run counts by flow id and state type. */
            flows: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** @description Run counts by state type. */
            runs: {
                [key: string]: number;
            };
            /** @description Task run counts by state type. */
            task_runs: {
                [key: string]: number;
            };
        };
        /**
         * @description Create a run by flow key, registering the flow when the server does not
         *     know it yet (offline handoff from another project).
         */
        CreateRunBody: {
            created_by?: string | null;
            description?: string | null;
            flow: string;
            flow_tags?: string[];
            module?: string | null;
            name?: string | null;
            options?: Record<string, never>;
            parameter_schema?: Record<string, never>;
            parameters?: Record<string, never>;
            project: string;
            source_dir?: string | null;
            tags?: string[];
        };
        CreateRunForFlowBody: {
            name?: string | null;
            parameters?: Record<string, never>;
            tags?: string[];
        };
        EmitEventBody: {
            /** Format: int64 */
            flow_id?: number | null;
            name: string;
            payload?: Record<string, never>;
            resource?: null | components["schemas"]["Resource"];
            /** Format: int64 */
            run_id?: number | null;
        };
        ErrorBody: {
            error: string;
        };
        Event: {
            external_id: components["schemas"]["Id"];
            /** Format: int64 */
            flow_id?: number | null;
            /** Format: int64 */
            id: number;
            name: string;
            occurred: components["schemas"]["i64"];
            payload?: Record<string, never>;
            related?: components["schemas"]["Resource"][];
            resource: components["schemas"]["Resource"];
            /** Format: int64 */
            run_id?: number | null;
            /**
             * Format: int64
             * @description Sequence number: the writer assigns ids in commit order.
             */
            seq: number;
        };
        EventsPage: {
            items: components["schemas"]["Event"][];
            /** Format: int64 */
            next_cursor?: number | null;
        };
        /** @description An armed expectation of a proactive rule. */
        Expectation: {
            armed_at: components["schemas"]["i64"];
            deadline: components["schemas"]["i64"];
            /** Format: int64 */
            flow_id?: number | null;
            /** Format: int64 */
            id: number;
            /** @description `run:<id>` or `flow:<id>`. */
            key: string;
            /** Format: int64 */
            rule_id: number;
            /** Format: int64 */
            run_id?: number | null;
            /** @description `open`, `met`, `lapsed`, or `cancelled`. */
            status: string;
        };
        FailedRequest: {
            engine_id: string;
            isolated?: boolean;
            module: string;
            /** Format: int32 */
            nice?: number;
            source_dir: string;
            traceback: string;
        };
        /** @description A registered flow. Identity is `(project, name)`. */
        Flow: {
            created_at: components["schemas"]["i64"];
            description?: string | null;
            error?: string | null;
            external_id: components["schemas"]["Id"];
            /** Format: int64 */
            id: number;
            last_seen_at: components["schemas"]["i64"];
            /** @description Whether the running server has this flow registered from code. */
            live?: boolean;
            module: string;
            name: string;
            options?: Record<string, never>;
            parameter_schema?: Record<string, never>;
            project: string;
            source_dir: string;
            tags?: string[];
        };
        /** @description Flow-level options declared in Python and stored as JSON on the flow row. */
        FlowOptions: {
            /** @default null */
            after: null | components["schemas"]["AfterSpec"];
            /**
             * Format: int64
             * @default null
             */
            crash_retries: number | null;
            /**
             * @description (count, window_seconds, persist_seconds)
             * @default null
             */
            disable_after: [
                number,
                number,
                number
            ] | null;
            /** @default false */
            has_bulk_complete: boolean;
            /** @default false */
            has_crash_hooks: boolean;
            /** @default false */
            isolated: boolean;
            /** @default false */
            log_prints: boolean;
            /**
             * Format: int64
             * @default null
             */
            max_concurrent: number | null;
            /**
             * @description `enqueue`, `skip`, or `cancel_new`.
             * @default
             */
            on_overlap: string;
            /**
             * Format: int64
             * @default 0
             */
            priority: number;
            resources?: Record<string, never>;
            /**
             * Format: int64
             * @default 0
             */
            retries: number;
            /** @default [] */
            schedules: components["schemas"]["ScheduleDecl"][];
            /**
             * Format: double
             * @default null
             */
            timeout_seconds: number | null;
        };
        FlowSummary: components["schemas"]["Flow"] & {
            /** @description The batch key of a keyed fan-in. */
            batch_key?: string | null;
            /**
             * @description Newest first: (run id, state type, state name, duration in microseconds
             *     or null while the run has none) of the last ten runs.
             */
            recent_runs: [
                number,
                string,
                string,
                number | null
            ][];
            schedules: components["schemas"]["ScheduleRow"][];
            /** @description The flow this one runs after, if any (the first upstream). */
            triggered_by?: string | null;
            /** @description Flows that run after this one. */
            triggers: string[];
            /** @description Every upstream of a fan-in flow (empty without `after=`). */
            upstreams?: string[];
        };
        GraphEdge: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
        };
        GraphNode: {
            /** Format: int64 */
            created_at: number;
            dynamic_key: string;
            /** Format: int64 */
            end_time?: number | null;
            external_id: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            start_time?: number | null;
            state: components["schemas"]["State"];
        };
        HeartbeatRequest: {
            engine_id: string;
            /** Format: int64 */
            run_id: number;
        };
        /** Format: int64 */
        i64: number;
        Id: string;
        Log: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            level: number;
            logger: string;
            message: string;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            task_run_id?: number | null;
            timestamp: components["schemas"]["i64"];
        };
        LogsPage: {
            items: components["schemas"]["Log"][];
            /** Format: int64 */
            next_cursor?: number | null;
        };
        PrefilterBody: {
            skip: string[];
        };
        PreviewBody: components["schemas"]["Schedule"] & {
            count?: number | null;
        };
        PreviewResponse: {
            next: number[];
            timezone: string;
        };
        ReleaseRequest: {
            /** Format: int64 */
            lease: number;
            /** Format: int64 */
            run_id: number;
        };
        ReportRequest: {
            engine_id: string;
            events: Record<string, never>[];
            /** Format: int64 */
            run_id: number;
        };
        ReportResponse: {
            applied: number;
            cancel: boolean;
            /** Format: int64 */
            last_seq: number;
            skipped: number;
        };
        /** @description What an event is about. */
        Resource: {
            id: string;
            /** @description `run`, `task_run`, `flow`, `schedule`, `rule`, or `custom`. */
            kind: string;
            name?: string;
        };
        ResumeBody: {
            /** @description The answer handed to `wait_for_input` on the resumed attempt (any JSON). */
            input: unknown;
        };
        RouteSpec: {
            id: number;
            method: string;
            path: string;
            /** @description Where the handler is defined (module and function), for the settings page. */
            source?: string | null;
        };
        /** @description One rule action. `kind` selects the variant; other fields are optional. */
        RuleAction: {
            /** @default null */
            body: string | null;
            /**
             * @description Name of the Python callable for `call` actions (code rules).
             * @default null
             */
            callable: string | null;
            /** @default null */
            flow: string | null;
            headers?: Record<string, never>;
            /**
             * @description `run_flow`, `cancel_run`, `set_state`, `pause_schedule`, `resume_schedule`, `webhook`, `email`, `call`.
             * @default
             */
            kind: string;
            /** @default null */
            message: string | null;
            /** @default null */
            method: string | null;
            parameters?: Record<string, never>;
            /** @default null */
            state_type: string | null;
            /** @default null */
            subject: string | null;
            /** @default [] */
            to: string[];
            /** @default null */
            url: string | null;
        };
        RuleBody: components["schemas"]["RuleSpec"] & {
            enabled?: boolean;
            name: string;
        };
        /** @description Clock of a clock-armed proactive rule: a cron expression in a timezone. */
        RuleClock: {
            /** @default  */
            cron: string;
            /** @default null */
            tz: string | null;
        };
        RuleFiring: {
            /** Format: int64 */
            event_id?: number | null;
            /** Format: int64 */
            id: number;
            outcomes: Record<string, never>[];
            /** Format: int64 */
            rule_id: number;
            /** Format: int64 */
            run_id?: number | null;
            timestamp: components["schemas"]["i64"];
        };
        /** @description Match clause of a rule. */
        RuleMatch: {
            /**
             * @description Event names, or prefixes ending in `*`.
             * @default []
             */
            events: string[];
            /** @default [] */
            flows: string[];
            /** @default null */
            project: string | null;
            /** @default [] */
            states: string[];
            /** @default [] */
            tags: string[];
        };
        RulePatch: {
            allow_self?: boolean | null;
            at?: Record<string, never>;
            /** Format: double */
            cooldown_seconds?: number | null;
            do?: components["schemas"]["RuleAction"][] | null;
            enabled?: boolean | null;
            /** Format: int64 */
            max_per_minute?: number | null;
            name?: string | null;
            once?: string | null;
            unless?: Record<string, never>;
            when?: Record<string, never>;
            /** Format: double */
            within?: number | null;
        };
        RuleRow: components["schemas"]["RuleSpec"] & {
            created_at: components["schemas"]["i64"];
            enabled: boolean;
            external_id: components["schemas"]["Id"];
            /** Format: int64 */
            fire_count: number;
            /** Format: int64 */
            id: number;
            last_fired?: null | components["schemas"]["i64"];
            module?: string | null;
            name: string;
            /** @description `ui` or `code`. */
            source: string;
            updated_at: components["schemas"]["i64"];
        };
        RuleSpec: {
            /** @default false */
            allow_self: boolean;
            /** @default null */
            at: null | components["schemas"]["RuleClock"];
            /**
             * Format: double
             * @default 0
             */
            cooldown_seconds: number;
            /** @default [] */
            do: components["schemas"]["RuleAction"][];
            /**
             * Format: int64
             * @default 60
             */
            max_per_minute: number;
            /**
             * @description `per_run` or `never`.
             * @default per_run
             */
            once: string;
            /** @default null */
            unless: null | components["schemas"]["RuleMatch"];
            /**
             * @default {
             *       "events": [],
             *       "flows": [],
             *       "project": null,
             *       "states": [],
             *       "tags": []
             *     }
             */
            when: components["schemas"]["RuleMatch"];
            /**
             * Format: double
             * @description Seconds after the arming event (or look-back before a clock tick).
             * @default null
             */
            within: number | null;
        };
        Run: {
            /** Format: int64 */
            attempt?: number;
            /** Format: int64 */
            backfill_id?: number | null;
            /** Format: int32 */
            crash_count: number;
            created_at: components["schemas"]["i64"];
            created_by?: string;
            end_time?: null | components["schemas"]["i64"];
            engine_id?: string | null;
            /** Format: int64 */
            engine_pid?: number | null;
            external_id: components["schemas"]["Id"];
            /** Format: int32 */
            failure_count: number;
            /** Format: int64 */
            flow_id: number;
            flow_name: string;
            /** Format: int64 */
            id: number;
            name: string;
            parameters?: Record<string, never>;
            /** Format: int64 */
            parent_run_id?: number | null;
            /** Format: int64 */
            priority?: number;
            project: string;
            /** Format: int64 */
            report_seq?: number;
            /** Format: int64 */
            schedule_id?: number | null;
            scheduled_time?: null | components["schemas"]["i64"];
            start_time?: null | components["schemas"]["i64"];
            state: components["schemas"]["State"];
            tags?: string[];
            /** @description Task runs of this run counted by state type; empty until tasks exist. */
            task_counts?: {
                [key: string]: number;
            };
            total_run_time?: null | components["schemas"]["i64"];
        };
        RunGraph: {
            edges: components["schemas"]["GraphEdge"][];
            nodes: components["schemas"]["GraphNode"][];
            /** Format: int64 */
            run_id: number;
        };
        RunsPage: {
            items: components["schemas"]["Run"][];
            /** Format: int64 */
            next_cursor?: number | null;
        };
        Schedule: {
            cron: string;
            day_or?: boolean;
            /** @enum {string} */
            kind: "cron";
            timezone?: string | null;
        } | {
            anchor?: null | components["schemas"]["i64"];
            /**
             * Format: double
             * @description Seconds between fires.
             */
            interval: number;
            /** @enum {string} */
            kind: "interval";
            timezone?: string | null;
        } | {
            /** @enum {string} */
            kind: "rrule";
            rrule: string;
            timezone?: string | null;
        };
        ScheduleBody: components["schemas"]["Schedule"] & {
            active?: boolean | null;
            catchup?: null | components["schemas"]["CatchupPolicy"];
            /** Format: int64 */
            catchup_max?: number | null;
            persist?: boolean | null;
        };
        ScheduleDecl: components["schemas"]["Schedule"] & {
            catchup?: components["schemas"]["CatchupPolicy"];
            /** Format: int64 */
            catchup_max?: number;
            key?: string | null;
        };
        SchedulePatchBody: {
            /** Format: int64 */
            anchor?: number | null;
            catchup?: null | components["schemas"]["CatchupPolicy"];
            /** Format: int64 */
            catchup_max?: number | null;
            cron?: string | null;
            day_or?: boolean | null;
            /** Format: double */
            interval?: number | null;
            persist?: boolean | null;
            rrule?: string | null;
            timezone?: string | null;
        };
        /**
         * @description Placeholders for later phases; defined now so the schema and API types
         *     are stable from the start.
         *     A stored schedule row: the schedule itself plus policy and bookkeeping.
         */
        ScheduleRow: {
            active: boolean;
            catchup: components["schemas"]["CatchupPolicy"];
            /** Format: int64 */
            catchup_max: number;
            code_key?: string | null;
            created_at: components["schemas"]["i64"];
            external_id: components["schemas"]["Id"];
            /** Format: int64 */
            flow_id: number;
            /** Format: int64 */
            id: number;
            next_fire?: null | components["schemas"]["i64"];
            paused_reason?: string | null;
            paused_until?: null | components["schemas"]["i64"];
            persist: boolean;
            schedule: components["schemas"]["Schedule"];
            /** @description `code` for schedules declared on the flow, `ui` for ones created at runtime. */
            source: string;
            updated_at: components["schemas"]["i64"];
        };
        ServerInfo: {
            engines: unknown[];
            home: string;
            /** Format: int32 */
            pid: number;
            queued: number;
            served_dir?: string | null;
            /** Format: int64 */
            started_at: number;
            /** Format: int64 */
            stream_seq: number;
            url: string;
            version: string;
        };
        Settings: {
            catchup_default: string;
            /** Format: int64 */
            crash_retries_default: number;
            custom_routes: components["schemas"]["RouteSpec"][];
            /** Format: int64 */
            database_bytes: number;
            database_path: string;
            email_configured: boolean;
            /** Format: int32 */
            engine_max_runs: number;
            engine_saturation_risk: boolean;
            home: string;
            host: string;
            max_engines: number;
            /** Format: int32 */
            pid: number;
            /** Format: int32 */
            port: number;
            resources: Record<string, never>;
            /** Format: int64 */
            retain_days: number;
            saturation_flows: string[];
            saturation_reason?: string | null;
            secret_key_missing: boolean;
            secret_key_present: boolean;
            served_dir?: string | null;
            version: string;
            /** Format: int64 */
            wal_bytes: number;
        };
        SettingsPatch: {
            /** Format: int64 */
            crash_retries?: number | null;
            resources?: {
                [key: string]: number;
            } | null;
            /** Format: int64 */
            retain_days?: number | null;
        };
        State: {
            details?: Record<string, never>;
            message?: string | null;
            name: string;
            timestamp: components["schemas"]["i64"];
            type: components["schemas"]["StateType"];
        };
        /** @enum {string} */
        StateType: "Scheduled" | "Pending" | "Running" | "Completed" | "Failed" | "Cancelled" | "Crashed" | "Paused" | "Cancelling";
        TaskRun: {
            /** Format: int32 */
            crash_count: number;
            created_at: components["schemas"]["i64"];
            dynamic_key: string;
            end_time?: null | components["schemas"]["i64"];
            external_id: components["schemas"]["Id"];
            /** Format: int32 */
            failure_count: number;
            /** Format: int64 */
            flow_id?: number;
            flow_name?: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** @description External ids of task runs this one waited on (futures and wait_for). */
            parents?: components["schemas"]["Id"][];
            project?: string;
            /** Format: int64 */
            run_id: number;
            run_name?: string;
            start_time?: null | components["schemas"]["i64"];
            state: components["schemas"]["State"];
            task_key: string;
            total_run_time?: null | components["schemas"]["i64"];
        };
        TaskRunsPage: {
            items: components["schemas"]["TaskRun"][];
            /** Format: int64 */
            next_cursor?: number | null;
        };
        TransitionBody: {
            details?: Record<string, never>;
            force?: boolean;
            message?: string | null;
            name?: string | null;
            type: components["schemas"]["StateType"];
        };
        TransitionRejected: {
            current?: null | components["schemas"]["State"];
            error: string;
            reason: string;
        };
        VariableBody: {
            name: string;
            overwrite?: boolean;
            secret?: boolean;
            tags?: string[];
            value: Record<string, never>;
        };
        VariablePatch: {
            secret?: boolean | null;
            tags?: string[] | null;
            value?: Record<string, never>;
        };
        VariableRow: {
            created_at: components["schemas"]["i64"];
            name: string;
            secret: boolean;
            tags?: string[];
            updated_at: components["schemas"]["i64"];
            /** @description Plain JSON value, or `"********"` for secrets in API responses. */
            value: Record<string, never>;
        };
        VariableWithRaw: components["schemas"]["VariableRow"] & {
            /** @description Ciphertext of a secret, present only when `raw=true` was requested. */
            raw?: string | null;
        };
        /** @description Work handed to an engine. */
        WorkItem: {
            cancel_requested: boolean;
            external_id: string;
            flow: string;
            /** @description `run`, `hooks`, or `bulk_complete`. */
            kind?: string;
            options: Record<string, never>;
            parameters: Record<string, never>;
            payload?: Record<string, never>;
            project: string;
            /** Format: int64 */
            run_id: number;
            run_name: string;
        };
        WorkRequest: {
            engine_id: string;
            isolated?: boolean;
            module: string;
            /** Format: int32 */
            nice?: number;
            /** Format: int32 */
            pid: number;
            source_dir: string;
            /**
             * Format: int64
             * @description Long-poll wait in milliseconds (max 30000).
             */
            wait_ms?: number;
        };
        WorkResponse: {
            exit?: boolean;
            run?: null | components["schemas"]["WorkItem"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_artifacts: {
        parameters: {
            query?: {
                /** @description Keyset cursor: the id of the last artifact of the previous page. */
                after?: number | null;
                flow?: string | null;
                key?: string | null;
                kind?: string | null;
                limit?: number | null;
                project?: string | null;
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactsPage"];
                };
            };
        };
    };
    create_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRow"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_backfill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_backfill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillStatus"];
                };
            };
        };
    };
    prefilter_backfill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrefilterBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    counts: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Counts"];
                };
            };
        };
    };
    failed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailedRequest"];
            };
        };
        responses: {
            /** @description Queued runs of the module failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description {cancel: bool, active: bool} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    work: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkResponse"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                after?: number | null;
                /** @description Ascending order when true (defaults to newest first). */
                ascending?: boolean;
                before?: number | null;
                /** @description Keyset cursor: the id of the last event of the previous page. */
                cursor?: number | null;
                flow_id?: number | null;
                limit?: number | null;
                /** @description Exact name, or a prefix ending in `*` (e.g. `run.*`). */
                name?: string | null;
                resource_id?: string | null;
                resource_kind?: string | null;
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
        };
    };
    emit_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmitEventBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_flows: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSummary"][];
                };
            };
        };
    };
    get_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSummary"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Flow is live */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_backfill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillStatus"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_backfills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillStatus"][];
                };
            };
        };
    };
    pause_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All schedules paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resume_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All schedules resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_run_for_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunForFlowBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Invalid parameters */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_schedules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRow"][];
                };
            };
        };
    };
    create_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRow"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upcoming_runs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acquire: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcquireRequest"];
            };
        };
        responses: {
            /** @description {lease: id} or {waiting: name} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRow"][];
                };
            };
        };
    };
    create_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRow"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRow"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRow"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rule_expectations: {
        parameters: {
            query?: {
                limit?: number | null;
                /** @description Only open (armed) expectations; default true. */
                open?: boolean | null;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expectation"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rule_firings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleFiring"][];
                };
            };
        };
    };
    test_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rendered actions against the latest matching event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                backfill_id?: number | null;
                /** @description Keyset cursor: the id of the last run of the previous page (id-ordered sorts only). */
                cursor?: number | null;
                flow?: string | null;
                flow_id?: number | null;
                limit?: number | null;
                name?: string | null;
                project?: string | null;
                schedule_id?: number | null;
                /** @description Only runs with a scheduled time after this (upcoming lists). */
                scheduled_after?: number | null;
                /** @description `created_desc` (default), `created_asc`, `start_desc`, `start_asc`, `duration_desc`, `duration_asc`, `name_asc`. */
                sort?: string | null;
                /** @description Inclusive lower bound on the run's start time (or creation when never started), microseconds. */
                start_after?: number | null;
                start_before?: number | null;
                state_name?: string | null;
                state_type?: string | null;
                /** @description Tags the run must carry; a query string may pass them comma-separated. */
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsPage"];
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Unknown flow and no module given */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_artifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRow"][];
                };
            };
        };
    };
    cancel_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_graph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGraph"];
                };
            };
        };
    };
    run_input: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description {input: <json>} or {input: null} when nothing was stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_logs: {
        parameters: {
            query?: {
                /** @description Return rows with id greater than this (keyset cursor). */
                after?: number | null;
                /** @description Minimum level: a Python numeric level or DEBUG, INFO, WARNING, ERROR, CRITICAL. */
                level?: string | null;
                limit?: number | null;
                search?: string | null;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsPage"];
                };
            };
        };
    };
    resume_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"][];
                };
            };
        };
    };
    transition_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionRejected"];
                };
            };
        };
    };
    delete_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchedulePatchBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRow"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pause_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRow"];
                };
            };
        };
    };
    resume_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRow"];
                };
            };
        };
    };
    preview_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfo"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    patch_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: {
                /** @description Last sequence number the client has seen. */
                since?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of run.updated, task_run.updated, log.appended, flow.registered, resync */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_task_runs: {
        parameters: {
            query?: {
                cursor?: number | null;
                flow?: string | null;
                limit?: number | null;
                name?: string | null;
                project?: string | null;
                run_id?: number | null;
                start_after?: number | null;
                start_before?: number | null;
                state_name?: string | null;
                state_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunsPage"];
                };
            };
        };
    };
    get_task_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    task_run_artifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRow"][];
                };
            };
        };
    };
    task_run_logs: {
        parameters: {
            query?: {
                /** @description Return rows with id greater than this (keyset cursor). */
                after?: number | null;
                /** @description Minimum level: a Python numeric level or DEBUG, INFO, WARNING, ERROR, CRITICAL. */
                level?: string | null;
                limit?: number | null;
                search?: string | null;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsPage"];
                };
            };
        };
    };
    list_variables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableRow"][];
                };
            };
        };
    };
    create_variable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariableBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableRow"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_variable: {
        parameters: {
            query?: {
                /** @description Return the stored ciphertext of a secret so a local client can decrypt it. */
                raw?: boolean | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableWithRaw"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_variable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_variable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariablePatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableRow"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
