// Fetch the server's OpenAPI document and regenerate src/api/schema.d.ts.
// Usage: node scripts/service-sync.mjs [--from URL|FILE] [--check]
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const args = process.argv.slice(2);
const fromIndex = args.indexOf("--from");
const from = fromIndex >= 0 ? args[fromIndex + 1] : process.env.CEREYAN_OPENAPI ?? "http://127.0.0.1:4200/api/openapi.json";
const check = args.includes("--check");
const target = path.resolve("src/api/schema.d.ts");

let document;
if (/^https?:/.test(from)) {
  const res = await fetch(from);
  if (!res.ok) throw new Error(`fetch ${from}: ${res.status}`);
  document = await res.text();
} else {
  document = readFileSync(from, "utf8");
}
const dir = mkdtempSync(path.join(tmpdir(), "cereyan-openapi-"));
const specPath = path.join(dir, "openapi.json");
writeFileSync(specPath, document);
const generated = execFileSync("npx", ["openapi-typescript", specPath, "--alphabetize"], { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] });
const banner = "// Generated by scripts/service-sync.mjs from the server's OpenAPI document. Do not edit.\n";
const output = banner + generated;
if (check) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== output) {
    console.error("src/api/schema.d.ts is out of date with the server's OpenAPI document; run `npm run service-sync`.");
    process.exit(1);
  }
  console.log("schema.d.ts is up to date");
} else {
  writeFileSync(target, output);
  console.log(`wrote ${target}`);
}
