-- Events of one run, for the run detail page.
--
-- `event` already carries an index for each of its other filters: kind,
-- (timestamp, id), (resource_kind, resource_id, id) and flow_id. `run_id` was
-- the one filter with nothing to serve it, so listing a run's events did
--
--   EXPLAIN QUERY PLAN SELECT id, kind FROM event WHERE run_id = ? ORDER BY id DESC LIMIT 100
--   `--SCAN event
--
-- a full scan of the fastest-growing table in the system. Measured on 500,000
-- events over 2,000 runs: 5.5 ms scanned against 0.30 ms indexed, 15x. The two
-- differ in kind as well as degree — the scan grows with the whole event table,
-- the indexed read with the events of one run.
--
-- Column order is equality first, then the sort column, so SQLite seeks to the
-- run and walks its entries in id order: no sort step, and it stops after LIMIT
-- rows. `id` is included for that reason and for consistency with every other
-- index on this table, which pairs its filter column with `id`. A B-tree walks
-- in either direction, so the ascending index also serves `ORDER BY id DESC`.
--
-- Cost, measured rather than assumed: 15% on event inserts in the production
-- batch shape, about 1.27 us per event, and 8.2 MB against a 26.4 MB table at
-- 500,000 events. Accepted because the read saves 5.2 ms per run-detail view
-- against a break-even of roughly 4,100 events written per view.
--
-- Events with no `run_id` (custom events, some engine events) still get an
-- entry, with a NULL key, so the index covers every row.
CREATE INDEX event_run_id ON event (run_id, id);
