"""Check the documentation conventions that a generator cannot enforce.

Counts the Python code blocks under ``docs/`` and checks that every skipped block gives a
reason: a block is skipped with ```` ```{.python notest} ```` and must be preceded, on the
line immediately above, by ``<!-- notest: reason -->``. Pages under ``docs/examples/`` are
rendered from ``examples/*.py``, which are tested as files, so they are not counted.

Also checks that ``docs/AGENTS.md`` exists and stays in step with the generated pages: every
page carrying a ``Generated by <script>`` marker must be named in the guide together with its
generator, and every generator the guide names must exist. Prints
``docs: N blocks tested, M skipped`` and exits non-zero on a violation.
"""

from __future__ import annotations

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
FENCE = re.compile(r"^```(\{\.?(?P<lang_b>[\w+-]+)(?P<opts>[^}]*)\}|(?P<lang>[\w+-]+)(?P<rest>.*))?\s*$")
REASON = re.compile(r"^<!--\s*notest:\s*\S.*-->\s*$")
MARKER = re.compile(r"<!--\s*Generated by (?P<script>\S+\.py)\b")
GUIDE = os.path.join(DOCS, "AGENTS.md")
GENERATOR = re.compile(r"`(?P<script>scripts/\S+\.py)`")


def check_guide(problems: list[str]) -> None:
    """`docs/AGENTS.md` must exist and list every generated page with its generator."""
    rel = os.path.relpath(GUIDE, ROOT)
    if not os.path.exists(GUIDE):
        problems.append(
            f"{rel}: missing; the authoring guide is what contributors and agents read"
            " before adding or changing a page under docs/"
        )
        return
    guide = open(GUIDE, encoding="utf-8").read()
    for path in sorted(glob.glob(os.path.join(DOCS, "**", "*.md"), recursive=True)):
        head = "".join(open(path, encoding="utf-8").readlines()[:10])
        m = MARKER.search(head)
        if not m:
            continue
        page = os.path.relpath(path, ROOT)
        script = m.group("script")
        if page not in guide:
            problems.append(f"{rel}: does not name the generated page {page}")
        elif script not in guide:
            problems.append(f"{rel}: names {page} without its generator {script}")
    for script in sorted(set(GENERATOR.findall(guide))):
        if not os.path.exists(os.path.join(ROOT, script)):
            problems.append(f"{rel}: names {script}, which does not exist")


def main() -> int:
    tested = skipped = 0
    problems: list[str] = []
    check_guide(problems)
    for path in sorted(glob.glob(os.path.join(DOCS, "**", "*.md"), recursive=True)):
        if os.path.relpath(path, DOCS).startswith("examples" + os.sep):
            continue
        lines = open(path, encoding="utf-8").read().splitlines()
        inside = False
        for n, line in enumerate(lines):
            m = FENCE.match(line)
            if not m:
                continue
            if inside:
                inside = False
                continue
            inside = True
            lang = m.group("lang_b") or m.group("lang") or ""
            opts = (m.group("opts") or m.group("rest") or "").split()
            if lang not in ("python", "py", "python3"):
                continue
            if "notest" in opts:
                skipped += 1
                if n == 0 or not REASON.match(lines[n - 1]):
                    problems.append(f"{os.path.relpath(path, ROOT)}:{n + 1}: notest block without a `<!-- notest: reason -->` line above it")
            else:
                tested += 1
    for p in problems:
        print(p)
    print(f"docs: {tested} blocks tested, {skipped} skipped")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
