"""Generate ``docs/reference/cli.md`` from the argparse parser in ``cereyan.cli``.

``--check`` exits non-zero when the committed page differs from what would be written.
"""

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "python"))

from cereyan import cli  # noqa: E402

OUT = os.path.join(ROOT, "docs", "reference", "cli.md")

EXIT_CODES = [
    ("EXIT_OK", "The run completed."),
    ("EXIT_FAILED", "The run failed."),
    ("EXIT_NOTHING_RAN", "Nothing ran: the store was locked and no server took the run."),
    ("EXIT_SCHEDULING", "The flow could not be loaded, a parameter did not coerce, a server was needed but unreachable or required a token, or a backfill argument was invalid."),
]


def _fmt_default(action: argparse.Action) -> str:
    if action.default in (None, False, argparse.SUPPRESS) or action.default == []:
        return ""
    return f" Default `{action.default}`."


def _positionals(parser: argparse.ArgumentParser) -> list[argparse.Action]:
    return [a for a in parser._actions if not a.option_strings and not isinstance(a, argparse._SubParsersAction)]


def _options(parser: argparse.ArgumentParser) -> list[argparse.Action]:
    return [a for a in parser._actions if a.option_strings and not isinstance(a, argparse._HelpAction)]


def _subparsers(parser: argparse.ArgumentParser) -> list[tuple[str, argparse.ArgumentParser]]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return list(action.choices.items())
    return []


def _usage(parser: argparse.ArgumentParser) -> str:
    return " ".join(parser.format_usage().replace("usage: ", "").split())


def _option_rows(actions: list[argparse.Action]) -> list[str]:
    rows = ["| Option | Meaning |", "|---|---|"]
    for a in actions:
        names = ", ".join(f"`{s}`" for s in a.option_strings)
        if a.nargs != 0 and not isinstance(a, argparse._StoreTrueAction):
            metavar = a.metavar or a.dest.upper()
            names += f" `{metavar}`"
        help_text = (a.help or "").rstrip(".")
        rows.append(f"| {names} | {help_text}.{_fmt_default(a)} |" if help_text else f"| {names} | {_fmt_default(a).strip()} |")
    return rows


def _positional_rows(actions: list[argparse.Action]) -> list[str]:
    rows = ["| Argument | Meaning |", "|---|---|"]
    for a in actions:
        help_text = (a.help or "").rstrip(".")
        optional = " (optional)" if a.nargs in ("?", "*") else ""
        rows.append(f"| `{a.dest}`{optional} | {help_text}. |" if help_text else f"| `{a.dest}`{optional} | |")
    return rows


def _command(name: str, parser: argparse.ArgumentParser, level: int, out: list[str]) -> None:
    out.append(f"{'#' * level} `cereyan {name}`")
    out.append("")
    if parser.description:
        out.append(parser.description)
        out.append("")
    out.append("```text")
    out.append(_usage(parser))
    out.append("```")
    out.append("")
    positionals = _positionals(parser)
    if positionals:
        out.extend(_positional_rows(positionals))
        out.append("")
    options = _options(parser)
    if options:
        out.extend(_option_rows(options))
        out.append("")
    for sub_name, sub in _subparsers(parser):
        _command(f"{name} {sub_name}", sub, level + 1, out)


def render() -> str:
    parser = cli.build_parser()
    out = [
        "# CLI",
        "",
        "<!-- Generated by scripts/gen_cli_reference.py from python/cereyan/cli.py. Do not edit; run `just docs`. -->",
        "",
        "The `cereyan` command. Every subcommand accepts the global options first, for example `cereyan --home /tmp/h run pipeline.py:etl`.",
        "",
        "```text",
        _usage(parser),
        "```",
        "",
        "## Global options",
        "",
    ]
    out.extend(_option_rows(_options(parser)))
    out.append("")
    for name, sub in _subparsers(parser):
        _command(name, sub, 2, out)
    out.append("## Exit codes")
    out.append("")
    out.append("Every command exits 0 on success and 3 on an error, printing the reason to standard error. `cereyan run` also uses 1 and 2 to report the outcome of the run.")
    out.append("")
    out.append("| Code | Constant | Meaning |")
    out.append("|---|---|---|")
    for const, meaning in EXIT_CODES:
        out.append(f"| {getattr(cli, const)} | `{const}` | {meaning} |")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if current != text:
            print(f"stale: {os.path.relpath(OUT, ROOT)} (run `just docs`)")
            return 1
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
