"""Generate ``docs/reference/events.md`` from the catalogue in ``crates/core``.

The event names, their payload fields, and the sentence saying when each fires
come from ``cereyan._core.event_names()``, which the emit sites are compiled
against. The page therefore cannot claim an event the engine does not record,
nor miss one it does.

The prose that is *not* in the catalogue lives here: the per-resource notes on
what a group's resource and related resources are, and the stream-message table,
whose names are SSE notifications rather than stored events.

``--check`` exits non-zero when the committed page differs from what would be written.
"""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "reference", "events.md")

PREAMBLE = """# Events

<!-- Generated by scripts/gen_events_reference.py from the catalogue in crates/core/src/events.rs. Do not edit; run `just docs`. -->

Every meaningful change is recorded as an event with a name, a sequence number, an occurred time, a resource (`run`, `task_run`, `flow`, `schedule`, `rule`, or `custom`), related resources, and a JSON payload. Rules match on events, the Events page and `GET /api/events` list them, and new ones arrive on the SSE stream as `event.created`.

The names below are the whole catalogue. It is declared once, in `crates/core/src/events.rs`, and every site that records an event names it from there, so this page is generated rather than maintained. `GET /api/vocabulary` serves the same list to the UI, and `cereyan.events` exposes it to Python: `events.run.failed` is the string `"run.failed"`.
"""

# Names under these prefixes belong to the engine; see `Custom events` below.
GROUPS = [
    ("run", "Run events", "Resource `run`; related `flow` and the run's tags. Offline the payload is `state` and `message` only."),
    ("task_run", "Task run events", "Resource `task_run` (id is the task run's external id, name its dynamic key); related `run` and `flow`. Offline the payload is `state` and `task_run`."),
    ("flow", "Flow events", "Resource `flow`."),
    ("schedule", "Schedule events", "Resource `schedule`, related `flow`."),
    ("resource", "Resource events", None),
    ("rule", "Rule events", "Resource `rule`, related the run and flow of the triggering event."),
]

NO_EVENT_NOTE = "`AwaitingRetry`, `AwaitingResource`, and `Cancelling` record no event."

RULE_FOOTER = """Runs created by a rule record `created_by = rule:<id>`, and a rule never fires on events of runs it created unless `allow_self` is set."""

CUSTOM = """## Custom events

`cereyan.emit_event(name, payload=None, resource=None)` records any name of your own. Inside a run the resource defaults to that run and the task run is recorded; outside a run the event goes to the store, or to the server's `POST /api/events` when one holds the store.

Names with a dot-separated prefix, such as `orders.table_empty`, match rules with `events: ["orders.*"]`.

The prefixes {prefixes} are the engine's. A name under one of them that is not in the catalogue above is rejected by `emit_event`, by `@app.rule`, and by the rules API, because nothing would ever emit it — a rule matching one could only ever sit silent. Every other name is yours and is never checked.
"""

STREAM = """## Stream messages

The SSE stream at `GET /api/stream` carries live notifications for the UI. They are not stored events and rules cannot match them, even where a name is shared with one: `run.updated` is a stream message, so a rule naming it is rejected.

| Message | Data | Sent when |
|---|---|---|
| `hello` | `latest`, `since` | The connection opens, before any backlog |
| `run.updated` | The run | A run was created or changed state |
| `task_run.updated` | The task run | A task run was created or changed state |
| `log.appended` | `run_id`, `last_id`, `count` | New log lines arrived |
| `event.created` | The event | Any event was recorded |
| `flow.registered` | The flow | A flow was registered or re-registered |
| `rule.updated` | The rule, or `id` and `deleted` | A rule was created, edited, fired, or deleted |
| `variable.updated` | The variable, or `name` and `deleted` | A variable was set or removed |
| `artifact.updated` | The artifact | A run published or updated an artifact |
| `schedule.updated` | The schedule, or `id` and `deleted` | A schedule was created, edited, paused, resumed, or deleted |
| `backfill.created` | `backfill_id`, `flow_id`, `count` | A backfill created its runs |
| `backfill.updated` | `backfill_id`, `cancelled` | A backfill was cancelled |
| `expectation.armed`, `expectation.met`, `expectation.lapsed` | `id`, `rule_id`, and the key or the event | A proactive rule armed, disarmed, or lapsed an expectation |
| `resync` | `latest` | The client asked for a sequence number older than the replay buffer; refetch everything |

Each message carries the sequence number as its SSE id. Reconnect with `?since=<seq>` to replay what was missed, or receive `resync` when the buffer no longer reaches back that far.
"""


def render() -> str:
    from cereyan import _core

    catalogue = _core.event_names()
    prefixes = _core.reserved_prefixes()
    by_resource: dict[str, list[tuple[str, str, list[str]]]] = {}
    for name, resource, when, fields in catalogue:
        by_resource.setdefault(resource, []).append((name, when, fields))

    out = [PREAMBLE]
    for resource, heading, note in GROUPS:
        rows = by_resource.get(resource, [])
        if not rows:
            continue
        out.append(f"## {heading}\n")
        if note:
            out.append(f"{note}\n")
        out.append("| Event | Payload | When |")
        out.append("|---|---|---|")
        for name, when, fields in rows:
            payload = ", ".join(f"`{f}`" for f in fields) or "empty"
            out.append(f"| `{name}` | {payload} | {when} |")
        out.append("")
        if resource == "run":
            out.append(f"{NO_EVENT_NOTE}\n")
        if resource == "rule":
            out.append(f"{RULE_FOOTER}\n")
    out.append(CUSTOM.format(prefixes=", ".join(f"`{p}`" for p in prefixes)))
    out.append(STREAM)
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if current != text:
            print(f"stale: {os.path.relpath(OUT, ROOT)} (run `just docs`)")
            return 1
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
